apiVersion: v1
kind: Pod
metadata:
  name: sfr-pod-chenghao-liu-4gpu
  namespace: sfr-ns-chenghao-liu
spec:
  restartPolicy: OnFailure
  volumes:
    - name: sfr-home-pv-chenghao-liu
      persistentVolumeClaim:
        claimName: sfr-home-pvc-chenghao-liu
  containers:
    - name: pytorch-nbeats-test
      image: "gcr.io/salesforce-research-internal/chliu-nbeats"
##      command: ["/bin/bash", "-c", "./allennlp/run.py train tutorials/getting_started/simple_tagger.json -s /stage/checkpoint/"]
      command: ["sleep", "720h"]
      #command: ["/bin/bash", "-c", "cd /export/home/N-BEATS && source /export/home/N-BEATS/.env"]
      resources:
        limits:
          nvidia.com/gpu: 4
          cpu: "15"
          memory: 90G
      volumeMounts:
        - name: sfr-home-pv-chenghao-liu
          mountPath: "/export/home"
  tolerations:
    - key: "gpu_num"
      operator: "Equal"
      value: "8"
      effect: "NoSchedule"